### PR TITLE
docs: use go install

### PR DESCRIPTION
**Pull request by georgettica**
this is the newer standard for installing binaries, so I updated accordingly

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Thanks. Can you re-title your commit and PR to `docs: use go install` please

**Comment by georgettica** [comment]
@06kellyjac done :)

**Comment by 06kellyjac** [comment]
Thanks for that. I also like the split between go versions.

Could you also pop `$ ` infront of the commands just to standardize with the other bash command blocks

**Comment by georgettica** [comment]
Should be ok now :)

**Review by 06kellyjac — APPROVED** [review]

**Pull request merged**
