### PR TITLE
feat: Add check for seccomp field

### PR DESCRIPTION
**Pull request by czunker**
Kubernetes 1.19 graduated seccomp to GA:
https://v1-19.docs.kubernetes.io/docs/setup/release/notes/#seccomp-graduates-to-general-availability

Currently, Kubernetes supports field and annotation.
The field is deprecated and Kubernetes 1.22 will remove it.

This PR is a suggestion for handling both.

Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Thanks for the submission :tada: Sorry I haven't looked at it sooner, I've been pretty busy.

Would you mind adding some bats tests too? (See the `test` folder) If you're not comfortable or too busy that's not a problem

**Comment by czunker** [comment]
No problem.
Will have a look at the bats tests tomorrow.

**Comment by czunker** [comment]
I added a test, but this fails because the checks verify against a schema version prior Kubernetes 1.19.

I'll have to figure out how to add the latest schema to the tests.

**Comment by czunker** [comment]
Tests pass now, but that got huge. I had to fix most of the test to match the new schema versions.

I also included a step to download a specific schema version, but that includes a Python module to parse the schema. For a clean approach, I would have to add venvs, and ...
Perhaps another approach could be the Docker image containing the schemas: https://github.com/controlplaneio/kubernetes-json-schema-container

**Comment by 06kellyjac** [comment]
Thanks for the updates @czunker I'll have a chat with Andy to find out how we want to manage the schemas going forward if the upstream repo isn't going to be updated anymore

**Pull request closed without merging**
